### PR TITLE
fix: enum as identifier name

### LINKED ISSUE #896: `Enum` is treated as a reserved word, even before PHP 8.1
Input: `class Enum {}`
Output: syntax error, unexpected 'Enum' (T_ENUM), expecting T_STRING

The official PHP parser seems to be able to handle this example even after PHP 8.1 - if that turns out to be too difficult to fix here, maybe should consider adding the keyword only for PHP >= 8.1?

Also see https://github.com/glayzzle/php-parser/pull/895 for a failing test.

### PR DESCRIPTION
**Pull request by czosel**
This seems much cleaner :-)

Fixes #896

### CODE REVIEW

File: src/lexer/tokens.js [hunk 1]
```diff
@@ -32,6 +32,21 @@ module.exports = {
...
+        return this.tok.T_STRING;
+      }
+      const initial = this.offset;
+      let ch = this.input();
+      while (ch == " ") {
+        ch = this.input();
+      }
+
+      const is_enum = this.is_LABEL_START();
+      this.unput(this.offset - initial);
```
Comment (MaartenStaa) [inline src/lexer/tokens.js:46]: I agree, this is much nicer! Thinking of how the PHP lexer handles this, I think this misses an edge case though. I think you need to look ahead through the entire label to check if it's not equal to `implements` or `extends`, to handle:

```php
class Enum extends Foo {}
class Enum implements Bar {}
```

**Review by MaartenStaa — CHANGES_REQUESTED** [review]

File: src/lexer/tokens.js (hunk 1 above)
Comment (czosel) [reply src/lexer/tokens.js]: Good call, I totally missed that! Fixed.

File: src/lexer/tokens.js [hunk 2]
```diff
@@ -41,10 +42,16 @@ module.exports = {
       while (ch == " ") {
         ch = this.input();
       }
+      let isEnum = false;
+      if (this.is_LABEL_START()) {
+        while (this.is_LABEL()) {
+          ch += this.input();
+        }
+        isEnum = !ch.startsWith("extends") && !ch.startsWith("implements");
```
Comment (MaartenStaa) [inline src/lexer/tokens.js:50]: Why `startsWith` rather than `!==`? I think you need to check for equality to cover e.g. `enum extendsType`. And come to think of it, I think you also need `ch.toLowerCase()`, since this is perfectly valid:

```php
class Enum exTEnds Foo {}
```

**Review by MaartenStaa — CHANGES_REQUESTED** [review]

File: src/lexer/tokens.js (hunk 2 above)
Comment (czosel) [reply src/lexer/tokens.js]: I was using startswith because `ch` contains one character too much (the first non-label character is appended in the last iteration. But you're right of course, `startsWith` is not what we need. Fixed, and also added `toLowerCase`.

Comment (MaartenStaa) [reply src/lexer/tokens.js]: Aah, gotcha. Yeah, that makes sense. LGTM now!

Comment (czosel) [reply src/lexer/tokens.js]: 🎉

**Comment by czosel** [comment]
Released in `v3.1.0-beta.9` :tada:
