### PR TITLE
fix: use PropertyStatement node for multiple properties

### LINKED ISSUE #256: invalid ast for multiple properties
Input:
```php
class Foo {
    private $dsn, $username, $password;
}
```

I will send a PR.

### PR DESCRIPTION
**Pull request by evilebottnawi**
fixes #256 + tests

### CODE REVIEW

File: src/ast.js [hunk 1]
```diff
@@ -296,8 +297,12 @@ AST.prototype.resolvePrecedence = function(result, parser) {
...
       }
     }
-  } else if (result.kind === "silent" && result.expr.right && !result.expr.parenthesizedExpression) {
-    // overall least precedence 
+  } else if (
+    result.kind === "silent" &&
+    result.expr.right &&
+    !result.expr.parenthesizedExpression
+  ) {
+    // overall least precedence
```
Comment (evilebottnawi) [inline src/ast.js]: Just prettier issue when you run `npm run test`

File: src/parser/class.js [hunk 2]
```diff
@@ -143,20 +145,24 @@ module.exports = {
       function read_variable_declaration() {
         const result = this.node("property");
         this.expect(this.tok.T_VARIABLE);
+        let propName = this.node("identifier");
```
Comment (evilebottnawi) [inline src/parser/class.js]: use `identifier` for property name

Comment (ichiriac) [reply src/parser/class.js]: :+1:
